services:
    minio:
        container_name: minIO
        image: minio/minio:latest
        command: server --console-address ":9001" /data/
        ports:
            - "9001:9001"
            - "9000:9000"
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        networks:
            - minio-sample
        volumes:
            - minio-storage:/data

    mysql:
        image: mysql:8.0@sha256:d58ac93387f644e4e040c636b8f50494e78e5afc27ca0a87348b2f577da2b7ff
        container_name: mysql-service
        ports:
            - 3306:3306
        networks:
            - minio-sample
        volumes:
            - .docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_USER=${MYSQL_USERNAME}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        depends_on:
            - minio

volumes:
    minio-storage:
    mysql:

networks:
    minio-sample:
        driver: bridge
