// <auto-generated />
using System;
using Api.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Infra.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Domain.UseCases.BusinessUnits.Models.BusinessUnit", b =>
                {
                    b.Property<int>("busId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("busName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("busId");

                    b.ToTable("business_unit");

                    b.HasData(
                        new
                        {
                            busId = 1,
                            busName = "Manaus",
                            createdAt = new DateTime(2024, 12, 17, 19, 6, 58, 133, DateTimeKind.Utc).AddTicks(5196)
                        },
                        new
                        {
                            busId = 2,
                            busName = "Brasília",
                            createdAt = new DateTime(2024, 12, 17, 19, 6, 58, 133, DateTimeKind.Utc).AddTicks(5198)
                        },
                        new
                        {
                            busId = 3,
                            busName = "Rio de Janeiro",
                            createdAt = new DateTime(2024, 12, 17, 19, 6, 58, 133, DateTimeKind.Utc).AddTicks(5199)
                        },
                        new
                        {
                            busId = 4,
                            busName = "São Paulo",
                            createdAt = new DateTime(2024, 12, 17, 19, 6, 58, 133, DateTimeKind.Utc).AddTicks(5200)
                        },
                        new
                        {
                            busId = 5,
                            busName = "Fortaleza",
                            createdAt = new DateTime(2024, 12, 17, 19, 6, 58, 133, DateTimeKind.Utc).AddTicks(5201)
                        });
                });

            modelBuilder.Entity("Api.Domain.UseCases.EquipmentFamilys.Models.EquipmentFamily", b =>
                {
                    b.Property<int>("eqFamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("eqFamName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("eqFamId");

                    b.ToTable("equipment_family");
                });

            modelBuilder.Entity("Api.Domain.UseCases.TypesChecklists.Models.TypesChecklist", b =>
                {
                    b.Property<int>("chTypId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("chTypName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("chTypStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("chTypId");

                    b.ToTable("types_checklist");
                });

            modelBuilder.Entity("Api.Domain.UseCases.TypesEquipments.Models.TypesEquipment", b =>
                {
                    b.Property<int>("eqTypId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("eqTypName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("eqTypId");

                    b.ToTable("types_equipment");
                });
#pragma warning restore 612, 618
        }
    }
}
